name: LeetCode Trip

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.22.2

      - name: Install dependencies
        run: pnpm install

      - name: Execute unit tests
        run: pnpm run test

      - name: Pre compilation
        run: pnpm run build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info,./clover.xml
          directory: ./coverage/
          verbose: true

  deployment:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: sh ./leetcode-trip-deploy.sh
